[package]
name = "concat-mulidents"
version = "0.1.0"
edition = "2021"
description = "A simple library for concatenating multiple identifiers"
keywords = ["concat", "identifiers", "proc-macro"]
lincense = "Unlicense"

[lib]
proc-macro = true
